config/routes.rb
Rails.application.routes.draw do
  root to: "reminders#index"
  devise_for :users
  resources :reminders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :scheduled_at, presence: true
  validates :send_email_at, presence: true

  belongs_to :user

  # returns reminders where an reminder email should be sent the current day 
  scope :of_today, ->  {
    where("extract(year from reminders.send_email_at) = ?
          and extract(month from reminders.send_email_at) = ?
          and extract(day from reminders.send_email_at) = ?",
          Date.today.year , Date.today.month, Date.today.day)
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reminders, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  include ReminderOwnerFilter
  before_action :authenticate_user!
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]
  before_action :require_to_be_reminder_owner, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params.merge(user: current_user))

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.require(:reminder).permit(:title, :description, :scheduled_at, :send_email_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduled Reminders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-warning">
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <a class="navbar-brand font-weight-bolder font-italic text-white" href="<%= root_path %>">SR</a>

      <div class="d-flex flex-row bd-highlight d-none d-md-block d-xl-none">
       <% if user_signed_in? %>
         <div class="p-2 bd-highlight">
           <%= link_to new_reminder_path, class: 'btn transparent-btn' do %>
             <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
               <%= image_tag("add-outline.svg", size: "24") %>
             </span>
           <% end %>
         </div>
       <% end %>
     </div>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="<%= reminders_path %>">My Reminders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="<%= new_reminder_path %>">New Reminder</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to '#', class: 'nav-link' do %>
                <span class="badge badge-warning nav-link text-dark">Hey @<%= current_user.email %></span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'sign in', new_user_session_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'sign up', new_user_registration_path, class: 'nav-link text-white' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container container-fluid">
      <!-- Content here -->
      <% if notice.present? %>
        <br><div class="p-3 mb-2 bg-success text-white rounded"><%= notice %></div>
      <% end %>

      <% if alert.present? %>
        <br><div class="p-3 mb-2 bg-danger text-white rounded"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= simple_form_for(@reminder) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :scheduled_at %>
    <%= f.input :send_email_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<h1>Reminders</h1>

<% if @reminders.empty? %>
  <div class="card mb-4 text-white bg-info">
    <div class="card-body">
      You have no reminders set up at the moment
    </div>
  </div>
<% else %>
  <div class="row">
    <% @reminders.each do |reminder| %>
      <div class="col-sm-12 col-md-9 col-lg-6 col-xl-3">
        <div class="card mb-4 text-white bg-info">
          <div class="card-header"><h5 class="card-title"><%= reminder.title %></h5></div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-nowrap">
              <%= image_tag "alarm-outline.svg", size: "24" %><%= reminder.scheduled_at %>
            </h6>
            <h6 class="card-subtitle mb-2 text-nowrap">
              <%= image_tag "mail-outline.svg", size: "24" %><%= reminder.send_email_at %>
            </h6>
            <p class="card-text"><%= reminder.description %></p>
          </div>
          <div class="card-footer text-muted">
            <div class="container">
              <div class="row">
                <div class="col">
                  <%= link_to reminder, class: 'card-link' do %>
                    <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
                      <%= image_tag "eye-outline.svg", size: "24" %>
                    </span>
                  <% end %>
                </div>
                <div class="col">
                  <%= link_to edit_reminder_path(reminder), class: 'card_link' do %>
                    <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
                      <%= image_tag "build-outline.svg", size: "24" %>
                    </span>
                  <% end %>
                </div>
                <div class="col">
                  <%= link_to reminder, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
                      <%= image_tag "trash-outline.svg", size: "24" %>
                    </span>
                  <% end %>
                </div>
              </div>
            </div>
         </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<br>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<div class="card text-white bg-info mt-4">
  <div class="card-header"><%= @reminder.title %></div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @reminder.description %></p>
      <footer class="blockquote-footer text-white">
        <%= image_tag "alarm-outline.svg", size: "24" %>
        <%= @reminder.scheduled_at %>
      </footer>
      <footer class="blockquote-footer text-white">
        <%= image_tag "mail-outline.svg", size: "24" %>
        <%= @reminder.send_email_at %>
      </footer>
    </blockquote>
  </div>
  <div class="card-footer text-muted">
    <div class="container">
      <div class="row">
        <div class="col">
          <%= link_to reminders_path, class: 'card-link' do %>
            <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
              <%= image_tag "arrow-undo-outline.svg", size: "24" %>
            </span>
          <% end %>
        </div>
        <div class="col">
          <%= link_to edit_reminder_path(@reminder), class: 'card_link' do %>
            <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
              <%= image_tag "build-outline.svg", size: "24" %>
            </span>
          <% end %>
        </div>
        <div class="col">
          <%= link_to @reminder, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="badge badge-warning nav-link text-dark border-0" style="box-shadow: 0 0 1px 0 rgba(42, 42, 42, 0.4), 0 3px 4px 0 rgba(42, 42, 42, 0.2);">
              <%= image_tag "trash-outline.svg", size: "24" %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
 </div>
</div>